name: Mirror Substack Posts

on:
  workflow_dispatch:
  schedule:
    - cron: "15 9 * * *"   # daily 09:15 UTC

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install jsdom@22 @mozilla/readability@0.4.4 node-fetch@2

      - name: Mirror posts
        run: node scripts/mirror.js

      - name: Commit mirrored data (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/substack_mirrors.json
          git diff --cached --quiet || git commit -m "Update mirrored Substack posts"
          git push
