// sanity test: write a known object so newsletter can render
const fs = require("fs");
const path = require("path");
const OUT = path.join("_data", "substack_mirrors.json");

const results = [{
  title: "Sanity Post",
  url: "https://example.com",
  date: "2025-08-10T00:00:00Z",
  content: "<p>If you see this, mirror pipeline is wired.</p>"
}];

fs.writeFileSync(OUT, JSON.stringify(results, null, 2));
console.log("[mirror] wrote", results.length, "post(s) →", OUT);
