name: Mirror Substack Posts

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (main, full history)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Show repo state
        run: |
          echo "HEAD:" $(git rev-parse HEAD)
          ls -la
          echo "---- scripts ----"; ls -la scripts || true
          echo "---- _data ----";   ls -la _data   || true

      - name: Show script the runner will execute
        run: |
          echo "=== scripts/mirror_v2.js (runner copy) ==="
          nl -ba scripts/mirror_v2.js | sed -n '1,200p'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run sanity writer
        run: node scripts/mirror_v2.js

      - name: Commit mirrored data (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/substack_mirrors.json
          git diff --cached --quiet || git commit -m "Mirror: write sanity post (v2)"
          git push
