name: Update Substack Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "23 9 * * *"   # daily 09:23 UTC
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install rss-parser@3.13.0

      - name: Fetch Substack RSS and write _data/substack.json
        env:
          SUBSTACK_RSS: "https://YOUR-SUBDOMAIN.substack.com/feed"  # <— CHANGE THIS
        run: |
          node -e "
            const Parser=require('rss-parser');
            const fs=require('fs');
            const parser=new Parser({
              customFields: {
                item: ['content:encoded']    // pull full HTML if present
              }
            });
            (async ()=>{
              try{
                const feed=await parser.parseURL(process.env.SUBSTACK_RSS);
                const items=(feed.items||[]).slice(0,10).map(it=>({
                  title: it.title||'',
                  url: it.link||'',
                  date: it.isoDate||it.pubDate||'',
                  summary: (it.contentSnippet||'').replace(/\\s+/g,' ').trim(),
                  html: (it['content:encoded']||it.content||'')  // full HTML fallback
                }));
                fs.writeFileSync('_data/substack.json', JSON.stringify(items, null, 2));
              }catch(e){
                console.error('RSS fetch failed:', e);
                process.exit(1);
              }
            })();
          "

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/substack.json
          git diff --cached --quiet || git commit -m "Update Substack feed (full HTML)"
          git push
