name: Update Substack Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "23 9 * * *"
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install rss-parser@3.13.0

      - name: Fetch Substack RSS and write _data/substack.json
        env:
          SUBSTACK_RSS: "https://waypointinstitute.substack.com/feed"   # <- your subdomain feed
        run: |
          node -e "
            const Parser = require('rss-parser');
            const fs = require('fs');
            const parser = new Parser({
              requestOptions: {
                headers: {
                  'User-Agent': 'Mozilla/5.0 (compatible; WaypointBot/1.0)',
                  'Accept': 'application/rss+xml, application/xml;q=0.9, */*;q=0.8'
                }
              },
              customFields: { item: ['content:encoded'] }
            });
            (async ()=>{
              try{
                const feed = await parser.parseURL(process.env.SUBSTACK_RSS);
                const items = (feed.items||[]).slice(0,12).map(it=>({
                  title: it.title||'',
                  url: it.link||'',
                  date: it.isoDate||it.pubDate||'',
                  summary: (it.contentSnippet||'').replace(/\\s+/g,' ').trim(),
                  html: it['content:encoded'] || it.content || ''
                }));
                fs.writeFileSync('_data/substack.json', JSON.stringify(items, null, 2));
              } catch(e) {
                console.error('RSS fetch failed:', e);
                process.exit(1);
              }
            })();
          "

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/substack.json
          git diff --cached --quiet || git commit -m 'Update Substack feed'
          git push
