name: Update Substack Feed
on:
  workflow_dispatch:
  schedule:
    - cron: '17 */6 * * *'   # every 6 hours (adjust as you like)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Fetch Substack RSS
        run: node scripts/substack_rss.js
      - name: Commit JSON (if changed)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add _data/substack.json
            git commit -m "chore: update Substack feed"
            git push
          else
            echo "No changes."
          fi
